//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReestrUslugOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbtFormula
    {
        public int FormulaId { get; set; }
        public int NodeId { get; set; }
        public ReestrUslugOMS.enResultType ResultType { get; set; }
        public ReestrUslugOMS.enDataType DataType { get; set; }
        public string DataValue { get; set; }
        public ReestrUslugOMS.enOperation Operation { get; set; }
        public Nullable<double> FactorValue { get; set; }
    
        public virtual dbtNode Node { get; set; }
    }
}
