//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReestrUslugOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbtImportHistory
    {
        public int ImportHistoryId { get; set; }
        public ReestrUslugOMS.enImportTableNames Table { get; set; }
        public Nullable<System.DateTime> Period { get; set; }
        public int Count { get; set; }
        public ReestrUslugOMS.enImportStatus Status { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
