//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReestrUslugOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbtPlan
    {
        public int PlanId { get; set; }
        public ReestrUslugOMS.enReportMode Type { get; set; }
        public int RowNodeId { get; set; }
        public int ColNodeId { get; set; }
        public double Value { get; set; }
        public System.DateTime Period { get; set; }
    
        public virtual dbtNode ColNode { get; set; }
        public virtual dbtNode RowNode { get; set; }
    }
}
