//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReestrUslugOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbtUser
    {
        public int UserId { get; set; }
        public string Login { get; set; }
        public string Sid { get; set; }
        public bool ProgramSettings { get; set; }
        public bool ReportSettings { get; set; }
        public bool UserSettings { get; set; }
        public bool PlanDoc { get; set; }
        public bool PlanDep { get; set; }
        public Nullable<int> NodeId { get; set; }
    
        public virtual dbtNode Node { get; set; }
    }
}
