//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReestrUslugOMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EFModel : DbContext
    {
        public EFModel(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dbtFormula> dbtFormula { get; set; }
        public virtual DbSet<dbtNode> dbtNode { get; set; }
        public virtual DbSet<dbtUser> dbtUser { get; set; }
        public virtual DbSet<dbtPlan> dbtPlan { get; set; }
        public virtual DbSet<dbtImportHistory> dbtImportHistory { get; set; }
    
        public virtual ObjectResult<sp_ReportFactResult> sp_ReportFact(Nullable<System.DateTime> period1, Nullable<System.DateTime> period2, string mcod, Nullable<int> errId, Nullable<int> inoId)
        {
            var period1Parameter = period1.HasValue ?
                new ObjectParameter("period1", period1) :
                new ObjectParameter("period1", typeof(System.DateTime));
    
            var period2Parameter = period2.HasValue ?
                new ObjectParameter("period2", period2) :
                new ObjectParameter("period2", typeof(System.DateTime));
    
            var mcodParameter = mcod != null ?
                new ObjectParameter("mcod", mcod) :
                new ObjectParameter("mcod", typeof(string));
    
            var errIdParameter = errId.HasValue ?
                new ObjectParameter("errId", errId) :
                new ObjectParameter("errId", typeof(int));
    
            var inoIdParameter = inoId.HasValue ?
                new ObjectParameter("inoId", inoId) :
                new ObjectParameter("inoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ReportFactResult>("sp_ReportFact", period1Parameter, period2Parameter, mcodParameter, errIdParameter, inoIdParameter);
        }
    }
}
