//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReestrUslugOMS
{
    using System;
    
    public partial class sp_ReportFactResult
    {
        public string CodUsl { get; set; }
        public string CodOtd { get; set; }
        public string CodDoc { get; set; }
        public Nullable<int> Usl { get; set; }
        public Nullable<double> ColUsl { get; set; }
        public Nullable<double> UET { get; set; }
        public Nullable<int> UslDo3 { get; set; }
        public Nullable<int> UslPosle3 { get; set; }
        public Nullable<int> DispIn2Y { get; set; }
        public Nullable<System.DateTime> Period { get; set; }
    }
}
