//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReestrUslugOMS
{
    using System;
    
    public partial class sp_ReportPlanResult
    {
        public int RowNodeId { get; set; }
        public int ColNodeId { get; set; }
        public Nullable<double> Value { get; set; }
    }
}
